---
version: '3.7'

services:

  redis-ui:
    image: patrikx3/p3x-redis-ui:2023.10.252
    ports:
      - 7843:7843
    depends_on:
      - redis-master
    volumes:
      - ./p3x-redis-ui-settings:/settings

  redis-master:
    image: redis:7.2.3
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"

  redis-slave:
    image: redis:7.2.3
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - "./.data-slave:/data"

  # Instance 1
  redis-sentinel:
    build:
      context: ./redis-sentinel
    links:
      - redis-master

  # Instance 2
  redis-sentinel2:
    build:
      context: ./redis-sentinel
    links:
      - redis-master

  # Instance 3
  redis-sentinel3:
    build:
      context: ./redis-sentinel
    links:
      - redis-master
